-- 정산 마스터 테이블
CREATE TABLE TB_SETTLE (
    SETTLE_ID   NUMBER(18)     NOT NULL,
    MEMBER_ID   VARCHAR2(20)   NOT NULL,
    AMOUNT      NUMBER(18,2)   DEFAULT 0,
    STATUS      VARCHAR2(20),
    REG_DT      DATE,
    UPD_DT      DATE,
    CONSTRAINT PK_TB_SETTLE PRIMARY KEY (SETTLE_ID)
);

CREATE SEQUENCE SEQ_SETTLE START WITH 1 INCREMENT BY 1;
